# Generated by Django 4.2.11 on 2024-04-15 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_delete_childmuseum'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeofPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'TypeOfPlay',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityName', models.CharField(max_length=255)),
                ('subcategory', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.typeofplay')),
            ],
            options={
                'db_table': 'Activities',
            },
        ),
    ]
