# Generated by Django 5.0.4 on 2024-04-18 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csctest', '0005_typeofplay_activity'),
        ('csctest', '0005_typeofplay_pagetimespent_activity'),
    ]

    operations = [
    ]
